const FETCH_ALL_HEROES = 'FETCH_ALL_HEROES';
const FETCH_ALL_RACES = 'FETCH_ALL_RACES';
const FETCH_ALL_CLASSES = 'FETCH_ALL_CLASSES';
const FETCH_MOST_FAMOUS_HERO = 'FETCH_MOST_FAMOUS_HERO';
const FETCH_MOST_FAMOUS_RACE = 'FETCH_MOST_FAMOUS_RACE';
const FETCH_MOST_FAMOUS_WEAPON = 'FETCH_MOST_FAMOUS_WEAPON';
const FETCH_FIRST_NAMES = 'FETCH_FIRST_NAMES';
const FETCH_LAST_NAMES = 'FETCH_LAST_NAMES';
const OPEN_HERO_MODAL = 'OPEN_HERO_MODAL';
const MODIFY_HERO = 'MODIFY_HERO';
const LOADING = 'LOADING';

export {
    FETCH_ALL_HEROES,
    FETCH_ALL_RACES,
    FETCH_ALL_CLASSES,
    FETCH_MOST_FAMOUS_HERO,
    FETCH_MOST_FAMOUS_RACE,
    FETCH_MOST_FAMOUS_WEAPON,
    FETCH_FIRST_NAMES,
    FETCH_LAST_NAMES,
    OPEN_HERO_MODAL,
    MODIFY_HERO,
    LOADING
}